import streamlit as st
from fpdf import FPDF
from datetime import datetime, date
import hashlib

# -----------------------------------------------------------------------------
# CONFIGURATION & ASSETS
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="The Sovereign Vault",
    page_icon="🔒",
    layout="wide",
    initial_sidebar_state="collapsed" # Collapsed by default for login screen
)

# COLOR PALETTE
COLOR_BG = "#0E1117"
COLOR_SIDEBAR = "#161B22"
COLOR_GOLD = "#D4AF37"
COLOR_TEXT = "#FAFAFA"
COLOR_ACCENT = "#FFD700"

# -----------------------------------------------------------------------------
# CSS STYLING (THEME OVERRIDE)
# -----------------------------------------------------------------------------
def inject_custom_css():
    st.markdown(
        f"""
        <style>
        /* MAIN BACKGROUND */
        .stApp {{
            background-color: {COLOR_BG};
            color: {COLOR_TEXT};
            font-family: 'Courier New', Courier, monospace;
        }}
        
        /* SIDEBAR BACKGROUND */
        section[data-testid="stSidebar"] {{
            background-color: {COLOR_SIDEBAR};
        }}

        /* HEADERS */
        h1, h2, h3, h4, h5, h6 {{
            color: {COLOR_GOLD} !important;
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            text-transform: uppercase;
            letter-spacing: 2px;
        }}

        /* INPUT LABELS */
        .stTextInput label, .stDateInput label, .stNumberInput label, .stSelectbox label {{
            color: {COLOR_ACCENT} !important;
            font-weight: bold;
        }}

        /* BUTTON STYLING - GOLD ACCENT */
        div.stButton > button {{
            background-color: {COLOR_GOLD};
            color: #000000;
            border-radius: 4px;
            border: 1px solid {COLOR_GOLD};
            padding: 10px 24px;
            font-weight: bold;
            text-transform: uppercase;
            transition: all 0.3s ease;
            width: 100%;
        }}
        
        div.stButton > button:hover {{
            background-color: #F8F8F8;
            color: {COLOR_GOLD};
            border-color: {COLOR_GOLD};
            box-shadow: 0 0 15px rgba(212, 175, 55, 0.4);
        }}

        /* CHECKBOXES */
        .stCheckbox label {{
            color: {COLOR_TEXT};
        }}
        
        /* ERROR MESSAGE */
        .stAlert {{
            background-color: #330000;
            color: #FFcccc;
            border: 1px solid red;
        }}

        /* REMOVE STREAMLIT BRANDING */
        #MainMenu {{visibility: hidden;}}
        footer {{visibility: hidden;}}
        header {{visibility: hidden;}}
        
        /* DIVIDER */
        hr {{
            border-top: 1px solid {COLOR_GOLD};
        }}
        </style>
        """,
        unsafe_allow_html=True
    )

# -----------------------------------------------------------------------------
# PDF GENERATION LOGIC
# -----------------------------------------------------------------------------
class CertificatePDF(FPDF):
    def header(self):
        # Gold Border
        self.set_draw_color(212, 175, 55)  # Gold RGB
        self.set_line_width(1.5)
        self.rect(5, 5, 200, 287)  # A4 Border
        self.rect(7, 7, 196, 283)  # Inner Double Border
        
        self.set_font('Arial', 'B', 24)
        self.set_text_color(0, 0, 0)
        self.ln(20)
        self.cell(0, 10, 'CERTIFICATE OF SOVEREIGNTY', 0, 1, 'C')
        self.ln(5)
        self.set_draw_color(0, 0, 0)
        self.line(60, 45, 150, 45) # Underline
        self.ln(10)

    def footer(self):
        self.set_y(-25)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by The Sovereign Vault | {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 0, 'C')

def create_certificate(data):
    pdf = CertificatePDF()
    pdf.add_page()
    
    # Metadata Block
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Courier", "", 12)
    
    # Track Details
    pdf.ln(10)
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, f"ARTIST: {data['artist'].upper()}", 0, 1, 'C')
    pdf.cell(0, 10, f"TRACK: {data['track'].upper()}", 0, 1, 'C')
    
    pdf.ln(10)
    
    # Technical Specs
    pdf.set_font("Courier", "", 11)
    pdf.cell(0, 8, f"Date of Registration: {data['date']}", 0, 1, 'L')
    pdf.cell(0, 8, f"BPM: {data['bpm']} | KEY: {data['key']}", 0, 1, 'L')
    
    pdf.ln(10)
    
    # Origins
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "ORIGIN PROTOCOLS:", 0, 1, 'L')
    pdf.set_font("Courier", "", 11)
    
    human_contribs = []
    if data['h_lyrics']: human_contribs.append("Lyrics")
    if data['h_melody']: human_contribs.append("Melody")
    if data['h_prod']: human_contribs.append("Production")
    
    pdf.cell(0, 8, f"Human Contributions: {', '.join(human_contribs) if human_contribs else 'None'}", 0, 1, 'L')
    pdf.cell(0, 8, f"AI Assistance: {data['ai_tool']}", 0, 1, 'L')
    
    pdf.ln(15)
    
    # The Metadata String (The "Key")
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Courier", "B", 10)
    pdf.multi_cell(0, 8, f"METADATA HASH:\n{data['meta_string']}", 1, 'L', True)
    
    pdf.ln(30)
    
    # Signature
    pdf.line(110, 240, 190, 240)
    pdf.set_xy(110, 242)
    pdf.set_font("Arial", "", 10)
    pdf.cell(80, 5, "Authorized Signature", 0, 0, 'C')
    
    # Seal graphic (Simulated with circle)
    pdf.set_draw_color(212, 175, 55)
    pdf.set_line_width(2)
    pdf.circle(40, 235, 15)
    pdf.set_xy(25, 230)
    pdf.set_font("Times", "B", 10)
    pdf.cell(30, 10, "OFFICIAL", 0, 0, 'C')

    return pdf.output(dest='S').encode('latin-1')

# -----------------------------------------------------------------------------
# VIEW: AUTHENTICATED APP
# -----------------------------------------------------------------------------
def authenticated_app():
    # SIDEBAR
    with st.sidebar:
        st.title("NOETIC INPUT")
        st.markdown("---")
        artist = st.text_input("Artist Name", value="Unknown Artist")
        track = st.text_input("Track Title", value="Untitled No. 1")
        bpm = st.number_input("BPM", min_value=60, max_value=300, value=120)
        track_key = st.text_input("Musical Key", value="C Major")
        reg_date = st.date_input("Registration Date", date.today())
        
        st.markdown("### 🔒 SECURE VAULT")
        st.caption("All entries are immutable upon generation.")
        
        st.markdown("---")
        if st.button("LOGOUT"):
            st.session_state['authenticated'] = False
            st.rerun()

    # MAIN AREA
    st.title("THE SOVEREIGN VAULT")
    st.markdown(f"**PROTOCOL:** ESTABLISHING TRACK LINEAGE")
    st.markdown("---")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("HUMAN ORIGIN")
        st.markdown("Check all elements created by biological cognition:")
        h_lyrics = st.checkbox("Lyrics (Written by Human)")
        h_melody = st.checkbox("Melody (Composed by Human)")
        h_prod = st.checkbox("Production (Arranged by Human)")

    with col2:
        st.subheader("SYNTHETIC ASSISTANCE")
        st.markdown("Select AI models utilized in the workflow:")
        ai_tool = st.selectbox(
            "Primary AI Framework",
            ["None", "Suno", "Udio", "RVC", "Stable Audio", "Custom Model"]
        )
        ai_intensity = st.slider("AI Influence %", 0, 100, 0)

    # LOGIC GENERATION
    st.markdown("---")
    
    # Determine Class
    if ai_tool == "None" and h_lyrics and h_melody and h_prod:
        src_class = "BIO-ORGANIC"
        rights = "100%"
    elif ai_tool != "None" and (not h_lyrics and not h_melody):
        src_class = "SYNTHETIC-GENERATIVE"
        rights = "PROMPT-RIGHTS-ONLY"
    else:
        src_class = "CYBORG-HYBRID"
        rights = f"{100 - int(ai_intensity/2)}%"

    # Generate Hash/String
    raw_data = f"{artist}{track}{bpm}{src_class}".encode()
    unique_hash = hashlib.sha256(raw_data).hexdigest()[:16].upper()
    
    meta_string = (
        f"[ID: {unique_hash}] "
        f"[SRC: {src_class}] "
        f"[RIGHTS: {rights}] "
        f"[BPM: {bpm}] "
        f"[TOOL: {ai_tool.upper()}]"
    )

    # DISPLAY
    st.markdown(f"### GENERATED METADATA")
    st.code(meta_string, language="json")

    # ACTION
    if st.button("MINT CERTIFICATE OF SOVEREIGNTY"):
        
        # Prepare Data
        data = {
            "artist": artist,
            "track": track,
            "bpm": bpm,
            "key": track_key,
            "date": reg_date,
            "h_lyrics": h_lyrics,
            "h_melody": h_melody,
            "h_prod": h_prod,
            "ai_tool": ai_tool,
            "meta_string": meta_string
        }
        
        # Generate PDF
        pdf_bytes = create_certificate(data)
        
        st.success("METADATA LOCKED. CERTIFICATE GENERATED.")
        
        # Download Button
        st.download_button(
            label="DOWNLOAD OFFICIAL PDF",
            data=pdf_bytes,
            file_name=f"{artist}_{track}_Certificate.pdf",
            mime="application/pdf"
        )

# -----------------------------------------------------------------------------
# VIEW: LOGIN SCREEN
# -----------------------------------------------------------------------------
def login_screen():
    # Centering mechanism
    st.markdown("<br><br><br>", unsafe_allow_html=True)
    
    col1, col2, col3 = st.columns([1, 2, 1])
    
    with col2:
        st.markdown(f"<h1 style='text-align: center;'>THE GATEKEEPER</h1>", unsafe_allow_html=True)
        st.markdown("<div style='text-align: center; color: #888;'>AUTHENTICATION REQUIRED</div>", unsafe_allow_html=True)
        st.markdown("---")
        
        password = st.text_input("SOVEREIGN ACCESS KEY", type="password")
        
        if st.button("INITIATE PROTOCOL"):
            if password == "ARCHITECT2025":
                st.session_state['authenticated'] = True
                st.rerun()
            else:
                st.error("⚠ ACCESS DENIED. Restricted to Sovereign Academy Members.")

# -----------------------------------------------------------------------------
# MAIN CONTROLLER
# -----------------------------------------------------------------------------
def main():
    inject_custom_css()
    
    # Initialize Session State
    if 'authenticated' not in st.session_state:
        st.session_state['authenticated'] = False
    
    # Routing
    if not st.session_state['authenticated']:
        login_screen()
    else:
        authenticated_app()

if __name__ == "__main__":
    main()